### PR TITLE
Improve travis sh script and update readme

### PR DESCRIPTION
**Pull request by AlaaSarhan**

### CODE REVIEW

**Comment by mariushoch** [comment]
I don't think `MediaWikiCore` is a very good group name for these tests (especially given it seems to be only used here, but sounds like a way more generic thing). Maybe rather chose something like `TermStoreMediaWiki` or `TermStoreMediaWikiIntegration`.

**Comment by AlaaSarhan** [comment]
@mariushoch done .. I choose `TermStoreWithMediaWikiCore` and avoided using Integration as to not imply that the group is only used on integration tests but also on unit ones.

**Comment by AlaaSarhan** [comment]
I was too slow to fix another issue locally .. but pushed solution to master directly now .. sorry

**Comment by JeroenDeDauw** [comment]
Great to have independent stuff \o/

**Pull request merged**
